"""MusicWorks™ V4.3 — AI Usage Tracker: provenance, governance audit trail.

Scans existing generated asset metadata and records human/AI contribution.
Every AI-generated asset gets tracked. Founder approval is the final gate.
"""
import json
from datetime import datetime, timezone
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent.parent / "data"

CREATION_TYPES = [
    ("ai_generated",  "AI Generated",  "Fully generated by AI — no human edits", "#9B89D4"),
    ("ai_assisted",   "AI Assisted",   "Human prompted AI; AI produced the output", "#3B82F6"),
    ("human_edited",  "Human Edited",  "AI generated, then edited by a human", "#F59E0B"),
    ("human_created", "Human Created", "No AI involvement", "#22C55E"),
]
CREATION_TYPE_LABELS  = {k: l for k, l, _, _ in CREATION_TYPES}
CREATION_TYPE_COLORS  = {k: c for k, _, _, c in CREATION_TYPES}

PROVIDERS_LIST = [
    "claude", "veo", "leonardo", "google_imagen", "hedra", "elevenlabs",
    "heygen", "canva", "perplexity", "capcut", "vizard", "pictory", "mock",
]


# ── Scan generated assets ─────────────────────────────────────────────────────

def scan_ai_records(artist_id: str) -> list[dict]:
    """Scan data/generated/{artist_id}/*_meta.json and return usage records."""
    gen_dir = DATA_DIR / "generated" / artist_id
    records = []
    if not gen_dir.exists():
        return records

    for meta_file in sorted(gen_dir.glob("*_meta.json")):
        try:
            meta    = json.loads(meta_file.read_text(encoding="utf-8"))
            job_id  = meta.get("job_id", meta_file.stem.replace("_meta", ""))
            job     = _load_job(artist_id, job_id)

            records.append({
                "job_id":            job_id,
                "job_type":          job.get("job_type", ""),
                "job_label":         job.get("job_label", ""),
                "song_id":           job.get("song_id", ""),
                "song_title":        job.get("song_title", ""),
                "creation_type":     meta.get("creation_type", "ai_assisted"),
                "provider_used":     meta.get("provider_used", "mock"),
                "connector":         meta.get("connector", ""),
                "worker_used":       meta.get("worker_used", ""),
                "generated_at":      meta.get("generated_at", ""),
                "prompt_used":       meta.get("prompt_used", ""),
                "generation_time_ms": meta.get("generation_time_ms", 0),
                "mock":              meta.get("mock", True),
                "status":            job.get("status", ""),
                "approved":          job.get("status", "") in ("approved", "published"),
                "approved_at":       job.get("approved_at", ""),
                "phase":             job.get("phase", ""),
            })
        except Exception:
            pass

    return sorted(records, key=lambda r: r.get("generated_at", ""), reverse=True)


def scan_for_song(artist_id: str, song_id: str) -> list[dict]:
    """Filter scan_ai_records to a specific song."""
    return [r for r in scan_ai_records(artist_id) if r.get("song_id") == song_id]


def _load_job(artist_id: str, job_id: str) -> dict:
    try:
        from execution.production_queue import get_job
        j = get_job(artist_id, job_id)
        return j or {}
    except Exception:
        return {}


# ── Summary stats ─────────────────────────────────────────────────────────────

def ai_usage_summary(artist_id: str, song_id: str | None = None) -> dict:
    records = scan_for_song(artist_id, song_id) if song_id else scan_ai_records(artist_id)
    total   = len(records)
    if total == 0:
        return {"total": 0, "by_type": {}, "by_provider": {}, "approved": 0, "mock": 0}

    by_type     = {}
    by_provider = {}
    approved    = 0
    mock        = 0

    for r in records:
        ct = r.get("creation_type", "ai_assisted")
        by_type[ct] = by_type.get(ct, 0) + 1
        pv = r.get("provider_used", "mock")
        by_provider[pv] = by_provider.get(pv, 0) + 1
        if r.get("approved"):
            approved += 1
        if r.get("mock"):
            mock += 1

    return {
        "total":       total,
        "by_type":     by_type,
        "by_provider": by_provider,
        "approved":    approved,
        "mock":        mock,
        "approval_pct": int(approved / total * 100) if total else 0,
    }


# ── Governance report ─────────────────────────────────────────────────────────

def build_governance_report(artist_id: str, song_id: str | None = None) -> dict:
    """Full audit-trail governance report for a release."""
    records = scan_for_song(artist_id, song_id) if song_id else scan_ai_records(artist_id)
    summary = ai_usage_summary(artist_id, song_id)

    return {
        "artist_id":    artist_id,
        "song_id":      song_id or "all",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary":      summary,
        "records":      records,
        "disclaimer":   (
            "This report is an operational audit trail generated by MusicWorks™. "
            "It does not constitute legal advice, compliance certification, or guarantee "
            "of platform acceptance. All publishing decisions are made by the Founder."
        ),
    }
