"""Render Orchestrator — coordinates all agents and stores results in Asset Library."""
import json
from datetime import datetime, timezone
from pathlib import Path
from contracts.models import SongInput, CampaignPlan
from execution.asset_library import AssetLibrary
from execution import production_queue
from execution import campaign_store
from execution import brief_store
from execution.campaign_store import make_campaign_id
from execution.brief_dependencies import REGEN_GROUPS, REGEN_GROUP_JOB_TYPES
from brand_brain.brain_loader import load_context
import agents.social_media_agent as social_agent
import agents.blog_press_agent as blog_agent
import agents.video_production_agent as video_agent
import agents.thumbnail_agent as thumbnail_agent
import agents.growth_content_agent as growth_agent

_AGENT_MODULES = {
    "social_media_agent":    social_agent,
    "blog_press_agent":      blog_agent,
    "video_production_agent": video_agent,
    "thumbnail_agent":       thumbnail_agent,
    "growth_content_agent":  growth_agent,
}

_GROUP_STORE_METHOD = {
    "captions": "_store_social",
    "written":  "_store_written",
    "video":    "_store_video",
    "artwork":  "_store_thumbnails",
    "growth":   "_store_growth_content",
}

_GROUP_MOCK_OUTPUT = {
    "captions": "SOCIAL_MEDIA_OUTPUT",
    "written":  "BLOG_PRESS_OUTPUT",
    "video":    "VIDEO_PRODUCTION_OUTPUT",
    "artwork":  "THUMBNAIL_OUTPUT",
    "growth":   "GROWTH_CONTENT_OUTPUT",
}


# Maps Asset Library asset_type -> Production Queue job_type, so campaign
# assets generated by the wizard show up in Asset Review / Results / Home
# (which all read from production_queue, not Asset Library).
ASSET_TYPE_TO_JOB_TYPE = {
    "caption_instagram":   "instagram_reel",
    "caption_tiktok":      "tiktok",
    "caption_youtube":     "youtube_short",
    "caption_facebook":    "facebook_reel",
    "blog_post":           "blog",
    "press_release":       "press_release",
    "church_blurb":        "church_outreach",
    "video_package":       "cinematic_scenes",
    "thumbnail_concept":   "thumbnail_set",
    # Growth & Discovery Agent — asset_type keys match job_type keys 1:1.
    "website_copy":                  "website_copy",
    "artist_story":                  "artist_story",
    "behind_song_article":           "behind_song_article",
    "seo_title":                     "seo_title",
    "seo_description":               "seo_description",
    "seo_keywords":                  "seo_keywords",
    "hashtag_set":                   "hashtag_set",
    "playlist_pitch":                "playlist_pitch",
    "playlist_target_notes":         "playlist_target_notes",
    "genre_positioning":             "genre_positioning",
    "similar_artist_notes":          "similar_artist_notes",
    "discovery_copy":                "discovery_copy",
    "artist_bio_short":              "artist_bio_short",
    "artist_bio_long":               "artist_bio_long",
    "x_post":                        "x_post",
    "threads_post":                  "threads_post",
    "rumble_description":            "rumble_description",
    "community_post":                "community_post",
    "countdown_graphic":             "countdown_graphic",
    "release_announcement_graphic":  "release_announcement_graphic",
    "campaign_poster":               "campaign_poster",
}
DEFAULT_JOB_TYPE = "post_launch"

# Asset Review reads job content from data/generated/{artist_id}/{job_id}.md
# (same convention as execution/workers/veo_worker.py and ui/pages/production.py) —
# not from Asset Library's own file_path, so the bridge must also write here.
GEN_DIR = Path(__file__).parent.parent / "data" / "generated"


def _dedupe_key(job_type: str, record) -> str:
    """Distinguishes same-job_type siblings that legitimately coexist (e.g.
    thumbnail Concept A vs B) so a later regeneration can match a new
    alternative to the right lineage instead of any job of that type."""
    option = (record.metadata or {}).get("option", "")
    return f"{job_type}#{option}" if option else job_type


class RenderOrchestrator:
    def __init__(self, library: AssetLibrary, mock_mode: bool = False):
        self.library = library
        self.mock_mode = mock_mode

    def _get_agent_outputs(self, song: SongInput, campaign: CampaignPlan) -> tuple:
        """Return (social, written, video, thumb) dicts from real agents or mock data."""
        if self.mock_mode:
            from agents.mock_data import (
                SOCIAL_MEDIA_OUTPUT,
                BLOG_PRESS_OUTPUT,
                VIDEO_PRODUCTION_OUTPUT,
                THUMBNAIL_OUTPUT,
            )
            return SOCIAL_MEDIA_OUTPUT, BLOG_PRESS_OUTPUT, VIDEO_PRODUCTION_OUTPUT, THUMBNAIL_OUTPUT
        return (
            social_agent.run(song, campaign),
            blog_agent.run(song, campaign),
            video_agent.run(song, campaign),
            thumbnail_agent.run(song, campaign),
        )

    def run_campaign(self, song: SongInput, campaign: CampaignPlan, printer=print, brief: dict = None) -> list:
        """
        Run all creative agents for a campaign.
        Returns a list of AssetRecord objects for every asset stored.

        `brief` is the Live Creative Brief's current field values (execution/
        brief_store.py) -- every agent reads from the SAME dict, so no
        department forms its own independent interpretation of the campaign
        (V7 Constitution, Amendment I, Principle 1). Optional so this method's
        existing behavior is unchanged for any caller that doesn't have one yet.
        """
        all_assets = []
        cid = campaign.campaign_id
        source = "[MOCK]" if self.mock_mode else ""

        # Load Brand Brain once — injected into every agent call
        brand_context = "" if self.mock_mode else load_context(song.artist_id)
        if brand_context:
            printer(f"  -> Brand Brain loaded: {song.artist_id}")
        elif not self.mock_mode and song.artist_id:
            printer(f"  -> [WARN] No Brand Brain found for artist_id={song.artist_id!r} -- proceeding without brand context")

        # ── 1. Social Media Agent ─────────────────────────────────────────────
        printer(f"  -> Social Media Agent running... {source}")
        if self.mock_mode:
            from agents.mock_data import SOCIAL_MEDIA_OUTPUT
            social = SOCIAL_MEDIA_OUTPUT
        else:
            social = social_agent.run(song, campaign, brand_context=brand_context, brief=brief)

        if not social.get("parse_error"):
            all_assets += self._store_social(song, campaign, social)
            printer(f"    [OK] {len(all_assets)} caption assets stored")
        else:
            printer("    [WARN] Social Media Agent returned unparseable output -- raw text saved")
            self.library.store_text_asset(
                cid, song.song_id, "social_captions_raw",
                "Social captions (parse error -- review manually)",
                social.get("raw_text", ""), "social_captions_raw.txt"
            )

        # ── 2. Blog & Press Agent ─────────────────────────────────────────────
        printer(f"  -> Blog & Press Agent running... {source}")
        if self.mock_mode:
            from agents.mock_data import BLOG_PRESS_OUTPUT
            written = BLOG_PRESS_OUTPUT
        else:
            written = blog_agent.run(song, campaign, brand_context=brand_context, brief=brief)

        if not written.get("parse_error"):
            before = len(all_assets)
            all_assets += self._store_written(song, campaign, written)
            printer(f"    [OK] {len(all_assets) - before} written assets stored")
        else:
            printer("    [WARN] Blog & Press Agent returned unparseable output -- raw text saved")
            self.library.store_text_asset(
                cid, song.song_id, "written_assets_raw",
                "Written assets (parse error -- review manually)",
                written.get("raw_text", ""), "written_assets_raw.txt"
            )

        # ── 3. Video Production Agent ─────────────────────────────────────────
        printer(f"  -> Video Production Agent running... {source}")
        if self.mock_mode:
            from agents.mock_data import VIDEO_PRODUCTION_OUTPUT
            video = VIDEO_PRODUCTION_OUTPUT
        else:
            video = video_agent.run(song, campaign, brand_context=brand_context, brief=brief)

        if not video.get("parse_error"):
            before = len(all_assets)
            all_assets += self._store_video(song, campaign, video)
            printer(f"    [OK] {len(all_assets) - before} video package assets stored (manual Veo run required)")
        else:
            printer("    [WARN] Video Production Agent returned unparseable output -- raw text saved")

        # ── 4. Thumbnail & Art Agent ──────────────────────────────────────────
        printer(f"  -> Thumbnail & Art Agent running... {source}")
        if self.mock_mode:
            from agents.mock_data import THUMBNAIL_OUTPUT
            thumb = THUMBNAIL_OUTPUT
        else:
            thumb = thumbnail_agent.run(song, campaign, brand_context=brand_context, brief=brief)

        if not thumb.get("parse_error"):
            before = len(all_assets)
            all_assets += self._store_thumbnails(song, campaign, thumb)
            printer(f"    [OK] {len(all_assets) - before} thumbnail assets stored")
        else:
            printer("    [WARN] Thumbnail Agent returned unparseable output -- raw text saved")

        # ── 5. Growth & Discovery Agent ─────────────────────────────────────────
        printer(f"  -> Growth & Discovery Agent running... {source}")
        if self.mock_mode:
            from agents.mock_data import GROWTH_CONTENT_OUTPUT
            growth = GROWTH_CONTENT_OUTPUT
        else:
            growth = growth_agent.run(song, campaign, brand_context=brand_context, brief=brief)

        if not growth.get("parse_error"):
            before = len(all_assets)
            all_assets += self._store_growth_content(song, campaign, growth)
            printer(f"    [OK] {len(all_assets) - before} growth & discovery assets stored")
        else:
            printer("    [WARN] Growth & Discovery Agent returned unparseable output -- raw text saved")
            self.library.store_text_asset(
                cid, song.song_id, "growth_content_raw",
                "Growth & discovery assets (parse error -- review manually)",
                growth.get("raw_text", ""), "growth_content_raw.txt"
            )

        printer("  -> Syncing assets to Production Queue for review...")
        self._sync_to_production_queue(song, campaign, all_assets)
        printer(f"    [OK] {len(all_assets)} job(s) added to Asset Review")

        printer("  -> Running cross-department review...")
        self._run_reviews(song.artist_id, make_campaign_id(song.song_id), printer=printer)
        printer("    [OK] Boardroom ratings ready")

        return all_assets

    def _sync_to_production_queue(self, song: SongInput, campaign: CampaignPlan, assets: list) -> None:
        """Mirror every Asset Library record into a Production Queue job (status=review)
        so it shows up in Asset Review / Results / Home, which read from production_queue,
        not Asset Library. Also writes the content to data/generated/{artist_id}/{job_id}.md
        so Asset Review's content preview (which reads only that path) isn't empty."""
        out_dir = GEN_DIR / song.artist_id
        out_dir.mkdir(parents=True, exist_ok=True)

        # Deterministic per-song id (not CampaignPlan.campaign_id, which is
        # LLM-generated and not guaranteed unique) — links jobs to the
        # persisted Campaign record used by the Media Blitz Control Center.
        campaign_id = make_campaign_id(song.song_id)

        for record in assets:
            job_type = ASSET_TYPE_TO_JOB_TYPE.get(record.asset_type, DEFAULT_JOB_TYPE)
            job = production_queue.create_job(
                artist_id=song.artist_id,
                job_type=job_type,
                song_id=song.song_id,
                song_title=song.title,
                release_date=song.release_date,
                phase="launch",
                notes=record.asset_description,
                prompt=campaign.campaign_name,
                campaign_id=campaign_id,
                dedupe_key=_dedupe_key(job_type, record),
            )
            jid = job["job_id"]
            production_queue.add_output_file(song.artist_id, jid, record.file_path, label=record.file_name)
            production_queue.update_job_status(song.artist_id, jid, "review")

            (out_dir / f"{jid}.md").write_text(record.preview_text or "", encoding="utf-8")
            (out_dir / f"{jid}_meta.json").write_text(json.dumps({
                "job_id":        jid,
                "connector":     "Campaign Build (Agent Orchestra)",
                "provider_used": "claude_api" if not self.mock_mode else "mock",
                "worker_used":   record.rendered_by,
                "mock":          self.mock_mode,
                "generated_at":  datetime.now(timezone.utc).isoformat(),
            }, indent=2), encoding="utf-8")

    # ── Cross-department review (V7 Phase 2) ──────────────────────────────────

    @staticmethod
    def _is_live_for_review(job: dict) -> bool:
        """A job counts as live-for-review if it's the current, actionable
        truth for its lineage. Excludes a fresh regeneration alternative that
        hasn't been approved yet -- reviewing it before the founder has even
        looked at it would make the Boardroom show a score for content that
        might get discarded (see the V7 Phase 2 plan's reconciled design)."""
        status = job.get("status")
        if status not in ("review", "approved", "scheduled", "published"):
            return False
        if job.get("alternative_of") and status == "review":
            return False
        return True

    def _live_content_for_target(self, artist_id: str, campaign_id: str, target: str) -> tuple[list[str], list[str]]:
        """Returns (content strings, job_ids) for every currently-live asset
        in a regen group, read from the same data/generated/{artist_id}/{job_id}.md
        path Asset Review itself reads from."""
        job_types = set(REGEN_GROUP_JOB_TYPES.get(target, []))
        jobs = production_queue.list_jobs(artist_id, campaign_id=campaign_id)
        live = [j for j in jobs if j.get("job_type") in job_types and self._is_live_for_review(j)]

        out_dir = GEN_DIR / artist_id
        contents, job_ids = [], []
        for job in live:
            f = out_dir / f"{job['job_id']}.md"
            if f.exists():
                contents.append(f.read_text(encoding="utf-8"))
                job_ids.append(job["job_id"])
        return contents, job_ids

    def _run_reviews(self, artist_id: str, campaign_id: str, targets: list[str] = None, printer=print) -> None:
        """Runs every review pairing whose target is in `targets` (all
        pairings if None), reading only currently-live content. Safe to call
        with a target that has no live content yet -- the reviewer still
        returns a rating (typically low), never fabricates one."""
        from execution.review_dependencies import REVIEW_PAIRINGS, REVIEWER_LABELS
        from execution import review_store
        from agents import review_agent

        pairings = [p for p in REVIEW_PAIRINGS if targets is None or p["target"] in targets]
        if not pairings:
            return

        brief_version = brief_store.get_current(artist_id, campaign_id)
        brief_fields = brief_version["fields"] if brief_version else {}
        brand_context = "" if self.mock_mode else load_context(artist_id)

        content_cache: dict[str, tuple[list[str], list[str]]] = {}
        for pairing in pairings:
            target = pairing["target"]
            if target not in content_cache:
                content_cache[target] = self._live_content_for_target(artist_id, campaign_id, target)
            contents, job_ids = content_cache[target]

            if self.mock_mode:
                result = review_agent.mock_rating(target, brief_fields)
            else:
                result = review_agent.run(
                    brief_fields, contents, pairing["lens"],
                    REVIEWER_LABELS.get(pairing["reviewer"], pairing["reviewer"]),
                    brand_context=brand_context,
                )

            review_store.save_review(
                artist_id, campaign_id, pairing["reviewer"], target,
                result["rating"], result["verdict"], job_ids,
            )
            # Constitutional Integrity Patch, P0: the founder-visible build log
            # shows the real verdict, never a bare "X/5" -- same reasoning as
            # the Boardroom's _RATING_OBSERVATION headlines (wizard.py).
            reviewer_label = REVIEWER_LABELS.get(pairing["reviewer"], pairing["reviewer"])
            printer(f"    {reviewer_label} reviewed {REGEN_GROUPS[target]['label']}: {result['verdict']}")

    def review_group(self, artist_id: str, campaign_id: str, target: str, printer=print) -> None:
        """Re-runs only the review pairings targeting one regen group. Called
        when the founder approves a regeneration alternative (the moment the
        live content for that group actually changes) -- never by
        regenerate_group itself, which only creates an unapproved alternative
        that isn't live yet."""
        self._run_reviews(artist_id, campaign_id, targets=[target], printer=printer)

    # ── Regeneration (V7 Constitution, Amendment I) ───────────────────────────

    def regenerate_group(self, artist_id: str, campaign_id: str, group_key: str, printer=print) -> dict:
        """Regenerates exactly one department's output against the campaign's
        CURRENT Live Creative Brief -- never the whole campaign (Principle 5).
        Every result is a brand-new alternative job/asset; no existing job is
        ever mutated, whatever its status (Principle 6-7). The founder decides
        in Asset Review whether an alternative replaces what it's an
        alternative to -- this method never makes that call automatically."""
        if group_key not in REGEN_GROUPS:
            raise ValueError(f"Unknown regeneration group: {group_key!r}")

        campaign_record = campaign_store.get_campaign(artist_id, campaign_id)
        if not campaign_record:
            raise ValueError(f"No campaign found for {campaign_id!r}")

        brief_version = brief_store.get_current(artist_id, campaign_id)
        brief_fields = brief_version["fields"] if brief_version else {}

        song_file_path = campaign_record.get("song_file_path", "")
        if not song_file_path or not Path(song_file_path).exists():
            raise ValueError("Original song file not found -- cannot regenerate without it.")
        song_data = json.loads(Path(song_file_path).read_text(encoding="utf-8"))
        song = SongInput.from_dict(song_data)

        # A throwaway CampaignPlan reconstructed from persisted data (it is
        # never itself persisted -- see the V7 Phase 1 plan). The 5 agents
        # only ever read campaign_mode/campaign_goal/ministry_angle, and the
        # Brief now carries better, founder-editable versions of the latter two.
        plan = CampaignPlan(
            campaign_id=campaign_id,
            campaign_name=campaign_record.get("campaign_name", ""),
            campaign_mode=campaign_record.get("campaign_mode", "blitz"),
            campaign_goal=brief_fields.get("campaign_goals", ""),
            platforms=[],
            content_calendar=[],
            risk_log=[],
            ministry_angle=brief_fields.get("core_message", ""),
            song_id=song.song_id,
        )

        brand_context = "" if self.mock_mode else load_context(artist_id)
        agent_module = _AGENT_MODULES[REGEN_GROUPS[group_key]["agent"]]
        store_method = getattr(self, _GROUP_STORE_METHOD[group_key])

        printer(f"Regenerating {REGEN_GROUPS[group_key]['label']}...")
        if self.mock_mode:
            from agents import mock_data
            data = getattr(mock_data, _GROUP_MOCK_OUTPUT[group_key])
        else:
            data = agent_module.run(song, plan, brand_context=brand_context, brief=brief_fields)

        if data.get("parse_error"):
            raise RuntimeError(f"{REGEN_GROUPS[group_key]['agent']} returned unparseable output during regeneration.")

        new_assets = store_method(song, plan, data)
        job_ids = self._sync_alternatives_to_production_queue(song, plan, new_assets, campaign_id)
        printer(f"  [OK] {len(job_ids)} alternative(s) ready for your review")
        return {"group": group_key, "alternatives_created": len(job_ids), "job_ids": job_ids}

    def _sync_alternatives_to_production_queue(
        self, song: SongInput, campaign: CampaignPlan, assets: list, campaign_id: str
    ) -> list[str]:
        """Like _sync_to_production_queue, but every job is explicitly linked
        via `alternative_of` to the current head of its lineage instead of
        being a fresh, unlinked original -- and no existing job is ever
        touched, regardless of its status."""
        out_dir = GEN_DIR / song.artist_id
        out_dir.mkdir(parents=True, exist_ok=True)

        existing_jobs = production_queue.list_jobs(song.artist_id, campaign_id=campaign_id)
        new_job_ids = []

        for record in assets:
            job_type = ASSET_TYPE_TO_JOB_TYPE.get(record.asset_type, DEFAULT_JOB_TYPE)
            key = _dedupe_key(job_type, record)

            lineage = [
                j for j in existing_jobs
                if j.get("job_type") == job_type and j.get("dedupe_key", j.get("job_type")) == key
            ]
            lineage.sort(key=lambda j: j.get("created_at", ""))
            target = lineage[-1] if lineage else None

            job = production_queue.create_job(
                artist_id=song.artist_id,
                job_type=job_type,
                song_id=song.song_id,
                song_title=song.title,
                release_date=song.release_date,
                phase="launch",
                notes=record.asset_description,
                prompt=campaign.campaign_name,
                campaign_id=campaign_id,
                dedupe_key=key,
                alternative_of=target["job_id"] if target else "",
            )
            jid = job["job_id"]
            production_queue.add_output_file(song.artist_id, jid, record.file_path, label=record.file_name)
            production_queue.update_job_status(song.artist_id, jid, "review")

            (out_dir / f"{jid}.md").write_text(record.preview_text or "", encoding="utf-8")
            (out_dir / f"{jid}_meta.json").write_text(json.dumps({
                "job_id":        jid,
                "connector":     "Regeneration (Live Creative Brief)",
                "provider_used": "claude_api" if not self.mock_mode else "mock",
                "worker_used":   record.rendered_by,
                "mock":          self.mock_mode,
                "generated_at":  datetime.now(timezone.utc).isoformat(),
            }, indent=2), encoding="utf-8")

            new_job_ids.append(jid)
            existing_jobs.append(job)  # so a 2nd asset in this same call sees the 1st as prior lineage state if types match

        return new_job_ids

    # ── Private storage methods ───────────────────────────────────────────────

    def _store_social(self, song: SongInput, campaign: CampaignPlan, data: dict) -> list:
        assets = []
        cid = campaign.campaign_id
        sid = song.song_id
        slug = song.title.lower()

        platform_map = {
            "instagram": ("caption_instagram", "Instagram Reel caption + hashtags + pinned comment", ["instagram_reels"]),
            "tiktok": ("caption_tiktok", "TikTok caption + hashtags + first comment", ["tiktok"]),
            "youtube": ("caption_youtube", "YouTube Shorts title + description + hashtags", ["youtube_shorts"]),
            "facebook": ("caption_facebook", "Facebook Reel caption + hashtags", ["facebook_reels"]),
        }

        for platform, (atype, desc, targets) in platform_map.items():
            pdata = data.get(platform, {})
            if not pdata:
                continue

            if platform == "youtube":
                content = self._format_youtube(pdata)
            else:
                content = self._format_caption(platform, pdata)

            assets.append(self.library.store_text_asset(
                cid, sid, atype, desc, content,
                f"{slug}_{platform}_caption_v1.md",
                platform_targets=targets,
                metadata={
                    "posting_time": pdata.get("posting_time_recommendation", ""),
                    "posting_rationale": pdata.get("posting_time_rationale", ""),
                    "hashtag_count": len(pdata.get("hashtags", [])),
                }
            ))
        return assets

    def _store_written(self, song: SongInput, campaign: CampaignPlan, data: dict) -> list:
        assets = []
        cid = campaign.campaign_id
        sid = song.song_id
        slug = song.title.lower()

        # Blog post
        bp = data.get("blog_post", {})
        if bp:
            content = self._format_blog_post(bp)
            assets.append(self.library.store_text_asset(
                cid, sid, "blog_post",
                f"Blog post — {bp.get('title', 'HLANGANA')}",
                content, f"{slug}_blog_post_v1.md",
                metadata={"word_count": bp.get("word_count", 0), "primary_keyword": bp.get("primary_keyword", "")}
            ))

        # Press release
        pr = data.get("press_release", {})
        if pr:
            content = self._format_press_release(pr)
            assets.append(self.library.store_text_asset(
                cid, sid, "press_release",
                "Press release — gospel media distribution",
                content, f"{slug}_press_release_v1.md",
                requires_founder_input=pr.get("quote_requires_founder_rewrite", True),
                metadata={"quote_requires_founder_rewrite": pr.get("quote_requires_founder_rewrite", True)}
            ))

        # Church blurb
        cb = data.get("church_blurb", {})
        if cb:
            content = cb.get("content", "")
            assets.append(self.library.store_text_asset(
                cid, sid, "church_blurb",
                "Church outreach blurb — pastoral distribution",
                content, f"{slug}_church_blurb_v1.txt",
            ))

        return assets

    def _store_video(self, song: SongInput, campaign: CampaignPlan, data: dict) -> list:
        cid = campaign.campaign_id
        sid = song.song_id
        slug = song.title.lower()
        content = self._format_video_package(data)

        record = self.library.store_text_asset(
            cid, sid, "video_package",
            "Video storyboard + Veo prompts (manual production required)",
            content, f"{slug}_video_package_v1.md",
            platform_targets=["instagram_reels", "youtube_shorts", "tiktok", "facebook_reels"],
            metadata={
                "veo_clips": len(data.get("veo_job_plan", [])),
                "requires_manual_veo_run": True,
                "estimated_production_time": data.get("estimated_production_time", "3-4 hours"),
            }
        )
        return [record]

    def _store_thumbnails(self, song: SongInput, campaign: CampaignPlan, data: dict) -> list:
        assets = []
        cid = campaign.campaign_id
        sid = song.song_id
        slug = song.title.lower()

        for option, label in [("concept_a", "A"), ("concept_b", "B")]:
            concept = data.get(option, {})
            if not concept:
                continue
            content = self._format_thumbnail_concept(label, concept)
            assets.append(self.library.store_text_asset(
                cid, sid, "thumbnail_concept",
                f"Thumbnail Concept {label} — {concept.get('label', '')}",
                content, f"{slug}_thumbnail_concept_{label.lower()}_v1.md",
                metadata={"option": label, "canva_time": data.get("estimated_canva_time", "30–45 min")}
            ))
        return assets

    def _store_growth_content(self, song: SongInput, campaign: CampaignPlan, data: dict) -> list:
        assets = []
        cid = campaign.campaign_id
        sid = song.song_id
        slug = song.title.lower()

        def store(asset_type: str, title: str, content: str, metadata: dict = None):
            if not content:
                return
            assets.append(self.library.store_text_asset(
                cid, sid, asset_type, title, content,
                f"{slug}_{asset_type}_v1.md", metadata=metadata or {},
            ))

        simple_fields = [
            ("website_copy", "Website Copy"),
            ("artist_story", "Artist Story"),
            ("behind_song_article", "Behind the Song Article"),
            ("playlist_pitch", "Playlist Pitch Copy"),
            ("playlist_target_notes", "Playlist Target Notes"),
            ("genre_positioning", "Genre Positioning"),
            ("similar_artist_notes", "Similar Artist Notes"),
            ("discovery_copy", "Music Discovery Copy"),
            ("artist_bio_short", "Short Artist Bio"),
            ("artist_bio_long", "Long Artist Bio"),
            ("x_post", "X Post"),
            ("threads_post", "Threads Post"),
            ("rumble_description", "Rumble Description"),
            ("community_post", "Community Post"),
        ]
        for asset_type, title in simple_fields:
            store(asset_type, title, self._format_growth_simple(title, data.get(asset_type, {})))

        # SEO — one agent field, three separate deliverables/job types
        seo = data.get("seo", {})
        if seo:
            store("seo_title", "SEO Title", seo.get("seo_title", ""))
            store("seo_description", "SEO Description", seo.get("seo_description", ""))
            keywords = seo.get("seo_keywords", [])
            if keywords:
                store("seo_keywords", "SEO Keywords", "\n".join(f"- {k}" for k in keywords))

        # Hashtag set — three tiers in one document
        hashtags = data.get("hashtag_set", {})
        if hashtags:
            lines = ["# Hashtag Set\n"]
            for tier, label in [("core", "Core"), ("niche", "Niche"), ("community", "Community")]:
                tags = hashtags.get(tier, [])
                if tags:
                    lines.append(f"\n## {label}\n\n{' '.join(tags)}\n")
            store("hashtag_set", "Hashtag Set", "".join(lines))

        # Graphics — same description + Canva-instructions pattern as thumbnails
        for asset_type, title in [
            ("countdown_graphic", "Countdown Graphic"),
            ("release_announcement_graphic", "Release Announcement Graphic"),
            ("campaign_poster", "Campaign Poster"),
        ]:
            spec = data.get(asset_type, {})
            if spec:
                content = (
                    f"# {title}\n\n**Description:** {spec.get('description', '')}\n\n"
                    f"---\n\n## Canva Instructions\n\n{spec.get('canva_instructions', '')}\n"
                )
                store(asset_type, title, content)

        return assets

    # ── Formatting helpers ────────────────────────────────────────────────────

    @staticmethod
    def _format_caption(platform: str, data: dict) -> str:
        lines = [f"# {platform.title()} Caption\n"]
        lines.append(f"**Posting time:** {data.get('posting_time_recommendation', '')} — {data.get('posting_time_rationale', '')}\n\n")
        lines.append("---\n\n## Caption\n\n")
        lines.append(data.get("caption", "") + "\n\n")
        if data.get("pinned_comment"):
            lines.append("---\n\n## Pinned Comment\n\n")
            lines.append(data.get("pinned_comment") + "\n\n")
        if data.get("first_comment"):
            lines.append("---\n\n## First Comment\n\n")
            lines.append(data.get("first_comment") + "\n\n")
        return "".join(lines)

    @staticmethod
    def _format_youtube(data: dict) -> str:
        lines = ["# YouTube Shorts\n\n"]
        lines.append(f"**Posting time:** {data.get('posting_time_recommendation', '')} — {data.get('posting_time_rationale', '')}\n\n")
        lines.append(f"---\n\n## Title\n\n{data.get('title', '')}\n\n")
        lines.append(f"---\n\n## Description\n\n{data.get('description', '')}\n\n")
        tags = data.get("hashtags", [])
        if tags:
            lines.append(f"---\n\n## Hashtags\n\n{' '.join(tags)}\n\n")
        return "".join(lines)

    @staticmethod
    def _format_growth_simple(title: str, data: dict) -> str:
        """Handles the Growth & Discovery Agent's simple fields, which come back
        as either {"content": ...} or {"heading"/"title": ..., "body"/"content": ...}."""
        if not data:
            return ""
        heading = data.get("heading") or data.get("title")
        body = data.get("body") or data.get("content", "")
        if heading:
            return f"# {heading}\n\n{body}"
        return f"# {title}\n\n{body}"

    @staticmethod
    def _format_blog_post(data: dict) -> str:
        lines = [
            f"# {data.get('title', 'Blog Post')}\n\n",
            f"**Meta description:** {data.get('meta_description', '')}\n\n",
            f"**Primary keyword:** {data.get('primary_keyword', '')}\n\n",
            "---\n\n",
            data.get("content", ""),
        ]
        return "".join(lines)

    @staticmethod
    def _format_press_release(data: dict) -> str:
        quote_draft = data.get("founder_quote_draft", "")
        lines = [
            "# Press Release\n\n",
            "**FOR IMMEDIATE RELEASE**\n\n",
            f"## {data.get('headline', '')}\n\n",
            f"*{data.get('dateline', '')}*\n\n",
            data.get("body", ""),
            "\n\n---\n\n",
            "**⚠ DRAFT QUOTE — REPLACE WITH YOUR OWN WORDS:**\n\n",
            f'> "{quote_draft}"\n\n',
            "*(In the Approval Queue, type your own quote to replace this before approving.)*\n\n",
            "---\n\n",
            f"**About Fire & Flow Gospel:** {data.get('boilerplate_fire_and_flow', '')}\n\n",
            f"**About MindSpark MusicWorks™:** {data.get('boilerplate_musicworks', '')}\n\n",
            f"**Media Contact:** {data.get('contact_placeholder', '[NAME | EMAIL | PHONE]')}\n\n",
            "###\n",
        ]
        return "".join(lines)

    @staticmethod
    def _format_video_package(data: dict) -> str:
        lines = ["# Video Production Package\n\n"]
        lines.append(f"**Concept:** {data.get('concept_statement', '')}\n\n")
        lines.append(f"**Estimated production time:** {data.get('estimated_production_time', '')}\n\n")
        lines.append("---\n\n## Storyboard\n\n")
        for scene in data.get("storyboard", []):
            lines.append(f"### {scene.get('timecode', '')} — {scene.get('label', '')}\n\n")
            lines.append(f"**Visual:** {scene.get('visual', '')}\n\n")
            lines.append(f"**Audio:** {scene.get('audio', '')}\n\n")
            if scene.get("on_screen_text"):
                lines.append(f"**On-screen text:** {scene.get('on_screen_text')}\n\n")
            if scene.get("notes"):
                lines.append(f"**Notes:** {scene.get('notes')}\n\n")
        lines.append("---\n\n## Veo Job Plans (Run These Manually in V2)\n\n")
        for clip in data.get("veo_job_plan", []):
            lines.append(f"### Clip {clip.get('clip_number', '')} — {clip.get('label', '')}\n\n")
            lines.append(f"**Timecode in final video:** {clip.get('timecode_in_video', '')}\n\n")
            lines.append(f"**Duration:** {clip.get('duration_seconds', '')} seconds\n\n")
            lines.append(f"**Veo Prompt:**\n```\n{clip.get('veo_prompt', '')}\n```\n\n")
            lines.append(f"**Negative Prompt:**\n```\n{clip.get('negative_prompt', '')}\n```\n\n")
            if clip.get("style_notes"):
                lines.append(f"**Style Notes:** {clip.get('style_notes')}\n\n")
        lines.append("---\n\n## Production Notes (Human Assembly)\n\n")
        lines.append(data.get("production_notes_human", "") + "\n")
        return "".join(lines)

    @staticmethod
    def _format_thumbnail_concept(label: str, data: dict) -> str:
        lines = [f"# Thumbnail Concept {label} — {data.get('label', '')}\n\n"]
        lines.append(f"**Description:** {data.get('description', '')}\n\n")
        lines.append("---\n\n## Design Specification\n\n")
        for key, value in data.items():
            if key in ("label", "description", "canva_instructions"):
                continue
            if isinstance(value, list):
                lines.append(f"**{key.replace('_', ' ').title()}:** {', '.join(value)}\n\n")
            else:
                lines.append(f"**{key.replace('_', ' ').title()}:** {value}\n\n")
        lines.append("---\n\n## Canva Instructions\n\n")
        lines.append(data.get("canva_instructions", "") + "\n")
        return "".join(lines)
